[package]
name = "test-stm32"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
panic-halt = "0.2"
stm32f1xx-hal = { version = "0.10", features = ["stm32f103", "medium"] }
lcd-lcm1602-i2c = "0.1"
embedded-hal = "0.2"
hd44780-driver = "0.4.0"
nb = "1.1.0"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
